[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i386-target.json"

[target.i386-target]
rustflags = "-C link-arg=-Tlinker.ld"
